### ISSUE TITLE
Use Lollipop enhancements in Lollipop and above?

### ISSUE THREAD

**Issue by KennyGoers** [pwittchen/ReactiveBeacons#43]
I was dropping through the code hoping for a less aggressive scanning and noticed that this library is using the depreciated versions of the API. Any chances you've looked into updating that? Or is that accomplished using the depreciated methods for now as Google appears to be implanting the depreciated usages using the new BluetoothLeScanner

Thoughts?

**Comment by pwittchen** [comment]
Thank you for reporting that issue. I'll take a look on that. If you have any suggestions concerning improving library and removing deprecated API calls, you can write about that.

**Comment by pwittchen** [comment]
Documentation of the `BluetoothLeScanner`: http://developer.android.com/reference/android/bluetooth/le/BluetoothLeScanner.html
I'm leaving this link here for now for documentation purposes. I'll tak a closer look on that later. I think, new Android API can be utilized within existing or separate Observable, but it'll require some additional work - not just updating method calls.

**Comment by pwittchen** [comment]
I'll work on this update on `api-upgrade` branch in my free time. You can track my progress. Once it will be finished, I'll merge the feature branch to master branch and write about that in this issue.

**Comment by pwittchen** [comment]
I've added PR #44, which resolves that problem. Now, library has two BLE scan strategies:
- pre-Lollipop
- Lollipop (or newer)

Appropriate strategy is chosen dynamically basing on system version installed on the device.
Moreover, I added new method, which allows to implement custom BLE scan strategy.

This update is currently on a feature branch. I'll test it and merge to the master branch soon.

@KennyGoers You can test this update on a `api-upgrade` feature branch, if you want to.

**Comment by pwittchen** [comment]
PR merged. It's done. It will be available in the next release.

**Comment by KennyGoers** [comment]
Thank you, was away and didn't see your comments, I'll give it a shot with
branch of mine.

**Comment by pwittchen** [comment]
I've released v. 0.5.0 of the library. Please, take a look on the newest source code on the master branch and `REAMDE.md` file.
